# Generated by Django 2.2.16 on 2020-09-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenum', models.CharField(max_length=16, unique=True)),
                ('nickname', models.CharField(max_length=32)),
                ('gender', models.BooleanField(default=True)),
                ('birthday', models.DateField(default='2000-01-01')),
                ('avatar', models.ImageField(upload_to='icons')),
                ('location', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
